### ISSUE TITLE
Issue on Mac w/ 'from riverrem.REMMaker import REMMaker'

### ISSUE THREAD

**Issue by allycat0531** [OpenTopography/RiverREM#4]
I'm running the package on my MacBook and am fairly new to these kinds of projects/codes. I installed conda and was successful in running "conda install -c conda-forge riverrem" in terminal - it installed all the proper packages.

I hit a snag when running the line "from riverrem.REMMaker import REMMaker". I get this: "from: can't read /var/mail/riverrem.REMMaker". Is there something wrong with the directory I'm working in?

Thanks!

**Comment by klarrieu** [comment]
Sounds like you are trying to run the command from the Mac terminal instead of using Python. Type "python" first to enter the Python interpreter from the terminal; then you should be able to run it. 

Note that if you have multiple installs of Python, then you should also make sure that you first activated the conda environment you used to install RiverREM. For example, if you installed RiverREM in your conda environment named "base", then starting from the terminal you can type "conda activate base" and then "python". Then you can import riverrem and run Python code.

**Comment by allycat0531** [comment]
Great - that worked! Thanks so much. How long does it usually take the program to find the river centerline?

**Comment by klarrieu** [comment]
It depends on the DEM extent and number of rivers within the DEM. It can take a couple minutes the first time running it for a large area, but results are cached so that step should go a lot quicker when re-running. The main time cost on large DEMs is the interpolation step.
