### ISSUE TITLE
numpy not found

### ISSUE THREAD

**Issue by ainterrante** [OpenTopography/RiverREM#7]
>>> from riverrem.REMMaker import REMMaker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\RiverREM\riverrem\REMMaker.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

Issues with "numpy"?

**Comment by klarrieu** [comment]
Hello,

Can you provide more context? How did you install RiverREM? Are you calling python from within the correct conda environment? Numpy should be installed if the environment was created successfully.

**Comment by ainterrante** [comment]
git clone https://github.com/opentopography/RiverREM.git
cd RiverREM
conda env create -n riverrem --file environment.yml

RiverREM is installed in conda, then the only way I could run the RiverREM code was to open a python environment in terminal of conda. If there a better way to do this, I am all ears. 


python - i
from riverrem.REMMaker import REMMaker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\RiverREM\riverrem\REMMaker.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by ainterrante** [comment]
Also, I just want to say, thank you Kenneth for your prompt replies. I think its an incredible program, and I have been trying to get it to function for the past week or so. I'm a novice at python, so I appreciate any and all help available to get it to run properly.

**Comment by klarrieu** [comment]
No problem! Before running `python -i`, activate the conda environment named `riverrem` that was created by the `conda env create` command:

`conda activate riverrem`

After activating the conda environment, then when you call `python` it will be running the specific installation of python for that conda environment. Then you should be able to import the `riverrem` package successfully. Feel free to reach out if you are still having issues.

**Comment by ainterrante** [comment]
![Screenshot (101)](https://github.com/OpenTopography/RiverREM/assets/148266284/6f0df2de-7f2b-401e-859d-aea27d421019)

Functionality prevails!

Is there a way to manipulate the colorways with a bit more precision in make_rem_viz?

It also seems like the mainsteam Trinity River is the primary source for the REM, but the adjacent tributaries dont have as much detail as I'd hope, even though they are identified in Open Street Map, would this just need to be adjusted by defining the river centerline manually?

**Comment by klarrieu** [comment]
Glad you got it working! 

`REMMaker.make_rem_viz()` does coloring by applying a [named colormap from matplotlib](https://matplotlib.org/stable/gallery/color/colormap_reference.html) to log10 of the REM raster values, i.e. a linear colormap in log-space. The goal of that is to emphasize smaller topographic differences near the channel more strongly, which usually works nicely for less confined meandering rivers, but coloring can be trickier for steeper catchments.

For more coloring options, you can open the output REM raster (the REM itself, not the REM visualization) in a GIS program (e.g. QGIS, ArcGIS, etc.) and apply any [custom coloring/symbology](https://docs.qgis.org/3.28/en/docs/training_manual/rasters/changing_symbology.html) you like. Using a GIS program like this would be the easiest and most versatile way to have it colored exactly how you want. If you're comfortable using GIS, you could then overlay a semi-transparent hillshade of the DEM on your colorized REM to get the shadow effect as well.

And yes, by default it uses the centerline of the longest named river on OpenStreetMap within the input raster's domain (neglecting all other shorter rivers). To include multiple tributaries/forks, you'd need to provide a custom `centerline_shp` [shapefile input](https://opentopography.github.io/RiverREM/remindex.html) when you initialize `REMMaker()`. Using multiple tributaries can be tricky to color nicely too, since it is hard to have a smooth interpolation scheme across regions that are roughly equidistant from multiple separate tributaries with differing elevations. Nonetheless, I have seen people end up with nice results by using multiple tributaries for the centerline.

Hope that helps!
